name: focus_wheel
description: >-
  Focus Wheel - A professional, offline-first ADHD productivity app with agenda, timer, reminders, tasks, mood journal, analytics, and motivational feedback.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.8.4
  riverpod: ^2.4.9
  flutter_local_notifications: ^19.2.1
  fl_chart: ^0.71.0
  share_plus: ^11.0.0
  speech_to_text: ^7.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/quotes/
    - assets/i18n/
